language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - jruby-20mode
  - rbx-19mode
  - rbx-20mode
# TODO: remove when we get off zipruby
matrix:
  allow_failures:
    - rvm:
      - jruby-19mode
      - jruby-20mode
